---

- name:  'Установка параметров сетевых интерфейсов'
  hosts:
    - net
  become: True
  gather_facts: True
  roles:
    - gw
    - servers


- name: 'Управление и настройка iptables на хосте'
  hosts:
      inetRouter2
  become: True
  gather_facts: True
  roles:
    - gw_iptables

# - name:  'Установка параметров сетевых интерфейсов'
#   hosts:
#     - servers
#   become: True
#   gather_facts: False
#   roles:
#     - servers
