---

- name:  'Установка параметров сетевых интерфейсов'
  hosts:
    - net
  become: True
  gather_facts: True
  roles:
    - gw



- name: 'Управление и настройка iptables на хостах'
  hosts:
      inetRouter
      centralRouter
  become: True
  gather_facts: True
  roles:
    - gw_iptables

# - name:  'Установка параметров сетевых интерфейсов'
#   hosts:
#     - servers
#   become: True
#   gather_facts: False
#   roles:
#     - servers
